package com.java.classe.basica;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Contato.java
//  @ Date : 25/12/2016
//  @ Author : 
//
//

public class Contato {
	private int idContato;
	private String dtContato;
	private String numCelular;
	private String numFixo;
	private char indZap;
	private String nomeOperadora;
	private String endEmail;

    /**
     * @return the idContato
     */
    public int getIdContato() {
        return idContato;
    }

    /**
     * @param idContato the idContato to set
     */
    public void setIdContato(int idContato) {
        this.idContato = idContato;
    }

    /**
     * @return the numCelular
     */
    public String getNumCelular() {
        return numCelular;
    }

    /**
     * @param numCelular the numCelular to set
     */
    public void setNumCelular(String numCelular) {
        this.numCelular = numCelular;
    }

    /**
     * @return the indZap
     */
    public char getIndZap() {
        return indZap;
    }

    /**
     * @param indZap the indZap to set
     */
    public void setIndZap(char indZap) {
        this.indZap = indZap;
    }

    /**
     * @return the nomeOperadora
     */
    public String getNomeOperadora() {
        return nomeOperadora;
    }

    /**
     * @param nomeOperadora the nomeOperadora to set
     */
    public void setNomeOperadora(String nomeOperadora) {
        this.nomeOperadora = nomeOperadora;
    }

    /**
     * @return the endEmail
     */
    public String getEndEmail() {
        return endEmail;
    }

    /**
     * @param endEmail the endEmail to set
     */
    public void setEndEmail(String endEmail) {
        this.endEmail = endEmail;
    }

    /**
     * @return the dtContato
     */
    public String getDtContato() {
        return dtContato;
    }

    /**
     * @param dtContato the dtContato to set
     */
    public void setDtContato(String dtContato) {
        this.dtContato = dtContato;
    }

    /**
     * @return the numFixo
     */
    public String getNumFixo() {
        return numFixo;
    }

    /**
     * @param numFixo the numFixo to set
     */
    public void setNumFixo(String numFixo) {
        this.numFixo = numFixo;
    }
}
