package com.java.classe.basica;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enderecos.java
//  @ Date : 25/12/2016
//  @ Author : 
//
//

public class Enderecos {
	private int codEndereco;
	private String cep;
	private String endereco;
	private String bairro;
	private String cidade;
        private int cod_rua;
        private String txt_complamento;

    /**
     * @return the codEndereco
     */
    public int getCodEndereco() {
        return codEndereco;
    }

    /**
     * @param codEndereco the codEndereco to set
     */
    public void setCodEndereco(int codEndereco) {
        this.codEndereco = codEndereco;
    }

    /**
     * @return the cep
     */
    public String getCep() {
        return cep;
    }

    /**
     * @param cep the cep to set
     */
    public void setCep(String cep) {
        this.cep = cep;
    }

    /**
     * @return the endereco
     */
    public String getEndereco() {
        return endereco;
    }

    /**
     * @param endereco the endereco to set
     */
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    /**
     * @return the bairro
     */
    public String getBairro() {
        return bairro;
    }

    /**
     * @param bairro the bairro to set
     */
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    /**
     * @return the cidade
     */
    public String getCidade() {
        return cidade;
    }

    /**
     * @param cidade the cidade to set
     */
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    /**
     * @return the cod_rua
     */
    public int getCod_rua() {
        return cod_rua;
    }

    /**
     * @param cod_rua the cod_rua to set
     */
    public void setCod_rua(int cod_rua) {
        this.cod_rua = cod_rua;
    }

    /**
     * @return the txt_complamento
     */
    public String getTxt_complamento() {
        return txt_complamento;
    }

    /**
     * @param txt_complamento the txt_complamento to set
     */
    public void setTxt_complamento(String txt_complamento) {
        this.txt_complamento = txt_complamento;
    }


}
