package com.java.classe.basica;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.java
//  @ Date : 25/12/2016
//  @ Author : 
//
//

public class Pessoa {
	private int Id;
	private int Contato_id;
	private int Endereco_id;
	private String Nome;
	private String Aniversario;
	private String Religiao;
	private String Responsavel;
	private String Observacao;
	private String Programa;
	private char IndEstudo;
	private int Contador;
	private String FxEtaria;
	private String Origem;

	/**
	 * @return the Id
	 */
	public int getId() {
		return Id;
	}

	/**
	 * @param Id the Id to set
	 */
	public void setId(int Id) {
		this.Id = Id;
	}

	/**
	 * @return the Nome
	 */
	public String getNome() {
		return Nome;
	}

	/**
	 * @param Nome the Nome to set
	 */
	public void setNome(String Nome) {
		this.Nome = Nome;
	}

	/**
	 * @return the Aniversario
	 */
	public String getAniversario() {
		return Aniversario;
	}

	/**
	 * @param Aniversario the Aniversario to set
	 */
	public void setAniversario(String Aniversario) {
		this.Aniversario = Aniversario;
	}

	/**
	 * @return the Religiao
	 */
	public String getReligiao() {
		return Religiao;
	}

	/**
	 * @param Religiao the Religiao to set
	 */
	public void setReligiao(String Religiao) {
		this.Religiao = Religiao;
	}

	/**
	 * @return the Responsavel
	 */
	public String getResponsavel() {
		return Responsavel;
	}

	/**
	 * @param Responsavel the Responsavel to set
	 */
	public void setResponsavel(String Responsavel) {
		this.Responsavel = Responsavel;
	}

	/**
	 * @return the Observacao
	 */
	public String getObservacao() {
		return Observacao;
	}

	/**
	 * @param Observacao the Observacao to set
	 */
	public void setObservacao(String Observacao) {
		this.Observacao = Observacao;
	}

	/**
	 * @return the Contato_id
	 */
	public int getContato_id() {
		return Contato_id;
	}

	/**
	 * @param Contato_id the Contato_id to set
	 */
	public void setContato_id(int Contato_id) {
		this.Contato_id = Contato_id;
	}

	/**
	 * @return the Endereco_id
	 */
	public int getEndereco_id() {
		return Endereco_id;
	}

	/**
	 * @param Endereco_id the Endereco_id to set
	 */
	public void setEndereco_id(int Endereco_id) {
		this.Endereco_id = Endereco_id;
	}

	/**
	 * @return the Contador
	 */
	public int getContador() {
		return Contador;
	}

	/**
	 * @param Contador the Contador to set
	 */
	public void setContador(int Contador) {
		this.Contador = Contador;
	}

	/**
	 * @return the Programa
	 */
	public String getPrograma() {
		return Programa;
	}

	/**
	 * @param Programa the Programa to set
	 */
	public void setPrograma(String Programa) {
		this.Programa = Programa;
	}

	/**
	 * @return the IndEstudo
	 */
	public char getIndEstudo() {
		return IndEstudo;
	}

	/**
	 * @param IndEstudo the IndEstudo to set
	 */
	public void setIndEstudo(char IndEstudo) {
		this.IndEstudo = IndEstudo;
	}

	/**
	 * @return the FxEtaria
	 */
	public String getFxEtaria() {
		return FxEtaria;
	}

	/**
	 * @param FxEtaria the FxEtaria to set
	 */
	public void setFxEtaria(String FxEtaria) {
		this.FxEtaria = FxEtaria;
	}

	/**
	 * @return the Origem
	 */
	public String getOrigem() {
		return Origem;
	}

	/**
	 * @param Origem the Origem to set
	 */
	public void setOrigem(String Origem) {
		this.Origem = Origem;
	}
}
