package com.java.classe.basica;

//

import java.util.Date;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @JDBC
//  @ File Name : Produto.java
//  @ Date : @06/08/2016
//  @ Author : @Paulinho
//
//


public class Produto {
    private int IdProd;
    private String nomeProd;
    private String descProd;
    private float valProd;
    private float valCompra;
    private float valPago;
    private Date dtPagamento;
    private int qtdProd;
    private int qtdParcelas;
    
    public void setNomeProd(String nomeProd) {
        this.nomeProd = nomeProd;
    }
    
    public String getNomeProd() {
        return nomeProd;
    
    }
    
    public void setValor(float valProd) {
        this.valProd = valProd;
    }
    
    public float getValor() {
        return 0;
    
    }
    
    public float getValPago() {
        return 0;
    
    }
    
    public void setDtPgto(Date dtPgto) {
        this.dtPagamento = dtPgto;
    }
    
    public Date getDtPgto() {
        return dtPagamento;
    
    }
    
    public void setParcelas(int qtdParcelas) {
        this.qtdParcelas = qtdParcelas;
    }
    
    public int getQtdParcelas() {
        return 0;
    
    }
    
    public float getValTotal() {
        return 0;
    
    }

    /**
     * @return the qtdProd
     */
    public int getQtdProd() {
        return qtdProd;
    }

    /**
     * @param qtdProd the qtdProd to set
     */
    public void setQtdProd(int qtdProd) {
        this.qtdProd = qtdProd;
    }

    /**
     * @return the valCompra
     */
    public float getValCompra() {
        return valCompra;
    }

    /**
     * @param valCompra the valCompra to set
     */
    public void setValCompra(float valCompra) {
        this.valCompra = valCompra;
    }

    /**
     * @return the descProd
     */
    public String getDescProd() {
        return descProd;
    }

    /**
     * @param descProd the descProd to set
     */
    public void setDescProd(String descProd) {
        this.descProd = descProd;
    }
}
