/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.executaveis;
import com.java.classe.basica.*;
import java.awt.Color;
import java.awt.Window;
import java.util.List;
/**
 *
 * @author Paulinho
 */
public class ProjetoAdventista extends javax.swing.JFrame {

    /**
     * Creates new form VendasHnd
     */
    private int numSeq = 0;
    private int qtdRegCursor = 0;
    private int qtdRegF = 0;
    private int qtdRegB = 0;
    private int qtdReg  = 0;
    private int idContato = 0;
    private int idEndereco = 0;
    private char indZap;
    private char indEstudo;
    private String vNumCel = "";
    private String vNumFixo = "";
    private String vNumMatric = "0";
    private String vNumCep = "";
    private String vQtdCaracter = "";
    private String cboProgItem = "";
    private List<Pessoa> pessoas = null;
    private List<Contato> contatos = null;
    private List<Enderecos> enderecos = null;
    
    public ProjetoAdventista() {
        this.aparenciaTela();
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDeleta = new javax.swing.JButton();
        btnAtualiza = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnInsere = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cboOperadora = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNumCel = new javax.swing.JFormattedTextField();
        txtDtAniversario = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNumFixo = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNumMatric = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaMat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMissionario = new javax.swing.JTextField();
        txtReligiao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboFxEtaria = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtOrigem = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cboProg = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPesqNome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPesqId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        cboUf = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNumCep = new javax.swing.JFormattedTextField();
        txtCodRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObs = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel1.setText("Cadastro de Missionarios");

        btnDeleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Erase.png"))); // NOI18N
        btnDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletaActionPerformed(evt);
            }
        });

        btnAtualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Save.png"))); // NOI18N
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/List.png"))); // NOI18N
        jButton5.setText("Pesquisa Avançada");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnInsere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Add.png"))); // NOI18N
        btnInsere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsereActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Exit.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Back.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Forward.png"))); // NOI18N
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/Clear.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnInsere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAvancar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleta)
                    .addComponent(btnAtualiza)
                    .addComponent(btnInsere)
                    .addComponent(btnVoltar)
                    .addComponent(btnAvancar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton5))
                    .addComponent(btnLimpar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel2.setText("Nome:");

        cboOperadora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLARO", "OI", "TIM", "VIVO", "NEXTEL" }));

        jLabel17.setText("Aniversario:");

        jLabel18.setText("Email:");

        jLabel19.setText("Numero Celular:");

        jLabel20.setText("Operadora:");

        try {
            txtNumCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumCel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumCelFocusLost(evt);
            }
        });
        txtNumCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCelKeyTyped(evt);
            }
        });

        try {
            txtDtAniversario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" ##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtAniversario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtAniversario.setName(""); // NOI18N

        jLabel21.setText("Numero Fixo:");

        try {
            txtNumFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumFixo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumFixoFocusLost(evt);
            }
        });
        txtNumFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumFixoKeyTyped(evt);
            }
        });

        jLabel13.setText("Matricula:");

        txtNumMatric.setEditable(false);
        txtNumMatric.setToolTipText("Numero de Matricula. Ex: 001,002");

        txtAreaMat.setColumns(20);
        txtAreaMat.setRows(5);
        jScrollPane3.setViewportView(txtAreaMat);

        jLabel8.setText("Programa:");

        jLabel5.setText("Miss. Resp:");

        jLabel6.setText("Religião:");

        cboFxEtaria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JOVEM", "ADOLESCENTE", "ADULTO", "IDOSO", "CRIANÇA" }));

        jLabel7.setText("Faixa Etaria:");

        jLabel24.setText("Congregação de Origem:");

        cboProg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SABADO DE MANHÃ", "CULTO J.A", "DOMINGO", "QUARTA FEIRA", "OUTROS" }));
        cboProg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProgItemStateChanged(evt);
            }
        });

        jLabel25.setText("Programa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtEmail)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel18)
                                    .addComponent(txtNumMatric, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumCel, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtNumFixo)
                                    .addComponent(txtMissionario))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(cboOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrigem)
                                    .addComponent(jLabel24)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(41, 41, 41))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cboFxEtaria, 0, 1, Short.MAX_VALUE)
                                                .addGap(24, 24, 24)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDtAniversario))))))
                        .addGap(310, 310, 310))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(txtReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addComponent(cboProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumMatric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel17)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFxEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMissionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel9.setText("Por nome:");

        jLabel10.setText("Matricula:");

        jButton3.setText("Vai");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesqId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPesqId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereços", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel3.setText("Endereço:");

        cboUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "AL", "AP", "AC", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RN", "RR", "SC", "SP", "SE", "TO" }));

        jLabel12.setText("Complemento:");

        jLabel14.setText("Bairro:");

        jLabel15.setText("UF:");

        jLabel16.setText("CEP:");

        try {
            txtNumCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumCepFocusLost(evt);
            }
        });
        txtNumCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCepKeyTyped(evt);
            }
        });

        jLabel4.setText("Cod. Rua:");

        jLabel11.setText("Observações:");

        txtAreaObs.setColumns(20);
        txtAreaObs.setRows(5);
        jScrollPane1.setViewportView(txtAreaObs);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel3))
                                .addGap(0, 114, Short.MAX_VALUE))
                            .addComponent(txtBairro)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodRua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumCep, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/logo/logoiasd2.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(48, 48, 48)
                .addComponent(jLabel23)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Botão Vai.
        EntradaPadrao in = new EntradaPadrao();
        String query = "select p.idpessoa"                                                                   +
                       "      ,p.nome_pessoa"                                                                +
                       "      ,to_char(p.mes_ano_aniversario,'dd/mm') as mes_ano_aniversario"                +
                       "      ,p.religiao"                                                                   +
                       "      ,p.responsavel"                                                                +
                       "      ,p.obs"                                                                        +
                       "      ,p.prog_estudo"                                                                +
                       "      ,p.ind_estudo"                                                                 +
                       "      ,p.faixa_etaria"                                                               +
                       "      ,p.txt_origem "                                                                +
                       "      ,c.idcontato "                                                                 +
                       "      ,to_char(c.dt_contato,'dd/mm/yyyy') as dt_contato"                             +
                       "      ,e.txt_complemento"                                                            +
                       "      ,c.num_celular"                                                                +
                       "      ,c.num_fixo"                                                                   +
                       "      ,c.ind_zap"                                                                    +
                       "      ,c.operadora"                                                                  +
                       "      ,c.email"                                                                      +
                       "      ,e.cod_endereco"                                                               +  
                       "      ,e.endereco"                                                                   +
                       "      ,e.cep"                                                                        +
                       "      ,e.bairro"                                                                     +
                       "      ,e.cidade"                                                                     +
                       "      ,e.cod_rua"                                                                    +  
                       "  from pessoa p  "                                                                   +
                       "     , contato c"                                                                    +
                       "     , enderecos e "                                                                 +
                       "   where p.contato_idcontato = c.idcontato "                                         +
                       "     and p.enderecos_cod_endereco = e.cod_endereco";
                    if (!txtPesqNome.getText().equals("")){
                       query = query + " and upper(p.nome_pessoa) like '%"+txtPesqNome.getText().toUpperCase()+"%'";
                    }
                   
                    if (!txtPesqId.getText().equals("")){
                        query = query + " and p.idpessoa = to_number('"+txtPesqId.getText()+"','999999999')";
                    }   
                    
                    if (!txtPesqNome.getText().equals("") || !txtPesqId.getText().equals("")) { 
                        this.limpaTexto();
                        pessoas = null;
                        contatos = null;
                        enderecos = null;
                        qtdRegF = 0;
                        qtdRegB = 0;
                        qtdRegCursor = 0;

                        DaoSql ds = new DaoSql(query, 'P');
                        pessoas = ds.sqlConsulta();
                        contatos = ds.sqlConsultaCo();
                        enderecos = ds.sqlConsultaEnd();
                        qtdRegCursor = pessoas.size();
                        ds = null;

                        if (qtdRegCursor > 0){
                            in.exibeMensagem("Foram localizadas: " +qtdRegCursor+" Ocorrências", "Quantidade Registros", 1);
                            if (qtdRegCursor == 1){
                               btnAvancar.setEnabled(true);
                               btnDeleta.setEnabled(true);
                               btnAtualiza.setEnabled(true);
                            } else {
                               btnAvancar.setEnabled(true);
                               btnVoltar.setEnabled(false);
                               btnAtualiza.setEnabled(true);
                               btnDeleta.setEnabled(true);
                            }
                            btnInsere.setEnabled(false);
                        } else {
                            in.exibeMensagem("Nenhum registro localizado.", "Quantidade Registros", 2);
                            btnAvancar.setEnabled(false);
                            btnVoltar.setEnabled(false);
                            btnAtualiza.setEnabled(false);
                            btnDeleta.setEnabled(false);
                            btnInsere.setEnabled(true);
                        }
                   }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Voltar para tela inicial.
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Botão Pesquisa Avançada.
        new ConsultaMembros().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnInsereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsereActionPerformed
        // Botão Inserir.
        DaoSql ds = new DaoSql(null,'P');
        numSeq = ds.getSquencia();
        Pessoa p = new Pessoa();
        Enderecos ed = new Enderecos();
        Contato co = new Contato();
        EntradaPadrao in = new EntradaPadrao();
        boolean inserido;
        
        //Insere endereços.
        if (!vNumMatric.equals("-1")){
            ed.setCodEndereco(numSeq);
            ed.setCep(txtNumCep.getText());
            ed.setEndereco(txtEndereco.getText());
            ed.setBairro(txtBairro.getText());
            ed.setCidade(cboUf.getSelectedItem().toString());
            ed.setCod_rua(Integer.parseInt(txtCodRua.getText()));
            ed.setTxt_complamento(txtComplemento.getText());

            //Insere Contatos.
            co.setIdContato(numSeq);
            co.setDtContato(in.getDataLocal(null,null));
            co.setNumCelular(vNumCel);
            co.setNumFixo(vNumFixo);
            
            co.setIndZap(indZap);
            co.setEndEmail(txtEmail.getText());
            co.setNomeOperadora(cboOperadora.getSelectedItem().toString());

            //Insere dados pessoais.
            p.setId(Integer.parseInt(vNumMatric));
            p.setContato_id(numSeq);
            p.setEndereco_id(numSeq);
            p.setNome(txtNome.getText());
            p.setAniversario(txtDtAniversario.getText());
            p.setReligiao(txtReligiao.getText());
            p.setResponsavel(txtMissionario.getText());
            p.setObservacao(txtAreaObs.getText());
            if (cboProgItem.equals("OUTROS"))
            {
               p.setPrograma(txtAreaMat.getText());
            } else {
               p.setPrograma(cboProgItem);
            }
            if (indEstudo == 'S'){
                p.setIndEstudo('S');
            } else {
                p.setIndEstudo('N');
            }
            p.setFxEtaria(cboFxEtaria.getSelectedItem().toString());
            p.setOrigem(txtOrigem.getText());
            
            inserido = ds.sqlInsere(p,ed,co);

            if (!inserido)
            {
               in.exibeMensagem("Erro ao inserir os dados!", "Erro de inserção", 0);
            } else {
              in.exibeMensagem("Dados inseridos com sucesso.", "Cadastro realizado", 1);
              
              /*Limpa campos.*/
              this.limpaTexto();
              
              /*Insere nova matricula.*/
              vNumMatric = ds.getMatricula();
            if (!vNumMatric.equals("-1")){
              txtNumMatric.setText(vNumMatric);
            } 
            }
        }
    }//GEN-LAST:event_btnInsereActionPerformed
    private void limpaTexto(){
        
              txtNumCep.setText("");
              txtEndereco.setText("");
              txtBairro.setText("");
              txtEmail.setText("");
              txtNome.setText("");
              txtNumFixo.setText("");
              txtNumCel.setText("");
              txtComplemento.setText("");
              txtDtAniversario.setText("");
              txtReligiao.setText("");
              txtMissionario.setText("");
              txtAreaObs.setText("");
              txtAreaMat.setText("");
              txtCodRua.setText("");
              txtPesqNome.setText("");
              txtPesqId.setText("");
              txtOrigem.setText("");
              cboOperadora.setSelectedIndex(0);
              cboFxEtaria.setSelectedIndex(0);
              cboProg.setSelectedIndex(0);
              cboUf.setSelectedIndex(0);
    }
    private void navegaRegistro(char direcao){
     
     if ( direcao == 'F') { // Para frente   
        if (qtdRegF < qtdRegCursor) {
          this.limpaTexto();
            cboProgItem = pessoas.get(qtdRegF).getPrograma();
              txtNumMatric.setText(String.valueOf(pessoas.get(qtdRegF).getId()));
              txtNumCep.setText(enderecos.get(qtdRegF).getCep());
              txtEndereco.setText(enderecos.get(qtdRegF).getEndereco());
              txtBairro.setText(enderecos.get(qtdRegF).getBairro());
              txtEmail.setText(contatos.get(qtdRegF).getEndEmail());
              txtNome.setText(pessoas.get(qtdRegF).getNome());
              txtNumFixo.setText(contatos.get(qtdRegF).getNumFixo());
              txtNumCel.setText(contatos.get(qtdRegF).getNumCelular());
              indZap = contatos.get(qtdRegF).getIndZap();
              txtOrigem.setText(pessoas.get(qtdRegF).getOrigem());
              cboFxEtaria.setSelectedItem(pessoas.get(qtdRegF).getFxEtaria());
            if (!cboProgItem.equals("OUTROS")){ 
                 cboProg.setSelectedItem(pessoas.get(qtdRegF).getPrograma());
            }
            if ((cboProg.getSelectedIndex() == 0) || (cboProg.getSelectedIndex() == 4)){
                 txtAreaMat.setText(pessoas.get(qtdRegF).getPrograma());
                 txtAreaMat.setEnabled(true);
                 txtAreaMat.setEditable(true);
                 txtAreaMat.setBackground(Color.WHITE);
            }
              indEstudo = pessoas.get(qtdRegF).getIndEstudo();
              txtComplemento.setText(enderecos.get(qtdRegF).getEndereco());
              txtDtAniversario.setText(pessoas.get(qtdRegF).getAniversario());
              txtReligiao.setText(pessoas.get(qtdRegF).getReligiao());
              txtMissionario.setText(pessoas.get(qtdRegF).getResponsavel());
              txtAreaObs.setText(pessoas.get(qtdRegF).getObservacao());
              txtCodRua.setText(String.valueOf(enderecos.get(qtdRegF).getCod_rua()));
              txtComplemento.setText(enderecos.get(qtdRegF).getTxt_complamento());
              cboOperadora.setSelectedItem(contatos.get(qtdRegF).getNomeOperadora());
              cboUf.setSelectedItem(enderecos.get(qtdRegF).getCidade());
              idContato = contatos.get(qtdRegF).getIdContato();
              idEndereco = enderecos.get(qtdRegF).getCodEndereco();
          qtdRegF++;
          qtdRegB++;
          qtdReg = qtdRegF;
        } else {
            btnAvancar.setEnabled(false);
        }
        if (qtdRegCursor != 1){
          if(!btnVoltar.isEnabled()){
             btnVoltar.setEnabled(true);
          }
        }
     }   
     if (direcao == 'B') { // Voltar
        if (qtdRegB <= qtdRegCursor) {
         if(qtdRegB != 0){
              qtdRegB--;
              qtdRegF--;
              this.limpaTexto();
              cboProgItem = pessoas.get(qtdRegB).getPrograma();
              txtNumMatric.setText(String.valueOf(pessoas.get(qtdRegB).getId()));
              txtNumCep.setText(enderecos.get(qtdRegB).getCep());
              txtEndereco.setText(enderecos.get(qtdRegB).getEndereco());
              txtBairro.setText(enderecos.get(qtdRegB).getBairro());
              txtEmail.setText(contatos.get(qtdRegB).getEndEmail());
              txtNome.setText(pessoas.get(qtdRegB).getNome());
              txtNumFixo.setText(contatos.get(qtdRegB).getNumFixo());
              txtNumCel.setText(contatos.get(qtdRegB).getNumCelular());
              indZap = contatos.get(qtdRegB).getIndZap();
              indEstudo = pessoas.get(qtdRegB).getIndEstudo();
              txtOrigem.setText(pessoas.get(qtdRegB).getOrigem());
              cboFxEtaria.setSelectedItem(pessoas.get(qtdRegB).getFxEtaria());
              if (!cboProgItem.equals("OUTROS")){ 
                 cboProg.setSelectedItem(pessoas.get(qtdRegB).getPrograma());
              }
              if (cboProg.getSelectedIndex() == 0 || cboProg.getSelectedIndex() == 4){
                 txtAreaMat.setText(pessoas.get(qtdRegB).getPrograma());
                 txtAreaMat.setEnabled(true);
                 txtAreaMat.setEditable(true);
                 txtAreaMat.setBackground(Color.WHITE);
              }
              txtComplemento.setText(enderecos.get(qtdRegB).getEndereco());
              txtDtAniversario.setText(pessoas.get(qtdRegB).getAniversario());
              txtReligiao.setText(pessoas.get(qtdRegB).getReligiao());
              txtMissionario.setText(pessoas.get(qtdRegB).getResponsavel());
              txtAreaObs.setText(pessoas.get(qtdRegB).getObservacao());
              txtCodRua.setText(String.valueOf(enderecos.get(qtdRegB).getCod_rua()));
              txtComplemento.setText(enderecos.get(qtdRegB).getTxt_complamento());
              cboOperadora.setSelectedItem(contatos.get(qtdRegB).getNomeOperadora());
              cboUf.setSelectedItem(enderecos.get(qtdRegB).getCidade());
              idContato = contatos.get(qtdRegB).getIdContato();
              idEndereco = enderecos.get(qtdRegB).getCodEndereco();
              qtdReg = qtdRegB;
         } else {
             btnVoltar.setEnabled(false);
         }  
        }
       if(!btnAvancar.isEnabled()){
           btnAvancar.setEnabled(true);
       }
     }
    }
    private void atualizaDadosForm(){
      
        this.limpaTexto();
            cboProgItem = pessoas.get(qtdReg).getPrograma();
              txtNumMatric.setText(String.valueOf(pessoas.get(qtdReg).getId()));
              txtNumCep.setText(enderecos.get(qtdReg).getCep());
              txtEndereco.setText(enderecos.get(qtdReg).getEndereco());
              txtBairro.setText(enderecos.get(qtdReg).getBairro());
              txtEmail.setText(contatos.get(qtdReg).getEndEmail());
              txtNome.setText(pessoas.get(qtdReg).getNome());
              txtNumFixo.setText(contatos.get(qtdReg).getNumFixo());
              txtNumCel.setText(contatos.get(qtdReg).getNumCelular());
              indZap = contatos.get(qtdReg).getIndZap();
              txtOrigem.setText(pessoas.get(qtdReg).getOrigem());
              cboFxEtaria.setSelectedItem(pessoas.get(qtdReg).getFxEtaria());
            if (!cboProgItem.equals("OUTROS")){ 
                 cboProg.setSelectedItem(pessoas.get(qtdReg).getPrograma());
            }
            if ((cboProg.getSelectedIndex() == 0) || (cboProg.getSelectedIndex() == 4)){
                 txtAreaMat.setText(pessoas.get(qtdReg).getPrograma());
                 txtAreaMat.setEnabled(true);
                 txtAreaMat.setEditable(true);
                 txtAreaMat.setBackground(Color.WHITE);
            }
              indEstudo = pessoas.get(qtdReg).getIndEstudo();
              txtComplemento.setText(enderecos.get(qtdReg).getEndereco());
              txtDtAniversario.setText(pessoas.get(qtdReg).getAniversario());
              txtReligiao.setText(pessoas.get(qtdReg).getReligiao());
              txtMissionario.setText(pessoas.get(qtdReg).getResponsavel());
              txtAreaObs.setText(pessoas.get(qtdReg).getObservacao());
              txtCodRua.setText(String.valueOf(enderecos.get(qtdReg).getCod_rua()));
              txtComplemento.setText(enderecos.get(qtdReg).getTxt_complamento());
              cboOperadora.setSelectedItem(contatos.get(qtdReg).getNomeOperadora());
              cboUf.setSelectedItem(enderecos.get(qtdReg).getCidade());
              idContato = contatos.get(qtdReg).getIdContato();
              idEndereco = enderecos.get(qtdReg).getCodEndereco();  
    }
    
    private void txtNumCelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumCelFocusLost
        // Evento
        EntradaPadrao ep = new EntradaPadrao();
      if (!vQtdCaracter.equals("")){
        if (vQtdCaracter.length() < 11){
         ep.exibeMensagem("O Telefone movel deve ter 14 digitos. Ex: (21)98807-6089", "Telefone Celular", 2);  
        } else {
           int val = ep.exibeConfirmacao(null, "Possui Whatapp ?", "Opçoes de Celular.", 1, 3);
            if(val == 0){
               indZap = 'S';
                if (ep.exibeConfirmacao(null, "Participar do estudo biblico ?", "Grupo de Estudo.", 1, 3) != 0){
                    indEstudo = 'N';
                } else {
                    indEstudo = 'S';
                }
            } else {
               indZap = 'N';
            }
            vNumCel = txtNumCel.getText();
          }
        vQtdCaracter = "";
      } 
    }//GEN-LAST:event_txtNumCelFocusLost

    private void txtNumFixoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumFixoFocusLost
        // Evento telefone fixo.
        EntradaPadrao ep = new EntradaPadrao();
        if (!vQtdCaracter.equals("")){
            if (vQtdCaracter.length() < 10){
                ep.exibeMensagem("O Telefone fixo deve ter 13 digitos. Ex: (21)3004-2289", "Telefone Fixo", 2);
            } else {
                vNumFixo = txtNumFixo.getText();
            }
        }
        vQtdCaracter = "";
    }//GEN-LAST:event_txtNumFixoFocusLost

    private void txtNumFixoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumFixoKeyTyped
        // TODO add your handling code here:
        
        vQtdCaracter = vQtdCaracter + Character.toString(evt.getKeyChar());
        
    }//GEN-LAST:event_txtNumFixoKeyTyped

    private void txtNumCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCelKeyTyped
        // TODO add your handling code here:
        vQtdCaracter = vQtdCaracter + Character.toString(evt.getKeyChar());
    }//GEN-LAST:event_txtNumCelKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Inicio Matricula.
        DaoSql ds = new DaoSql(null,'P');
        vNumMatric = ds.getMatricula();
        if (!vNumMatric.equals("-1")){
            txtNumMatric.setText(vNumMatric);
        }    
      setExtendedState(MAXIMIZED_BOTH);
      btnAvancar.setEnabled(false);
      btnVoltar.setEnabled(false);
      btnAtualiza.setEnabled(false);
      btnDeleta.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        // Registro para frente.
        navegaRegistro('F');
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Registro para traz.
        navegaRegistro('B');
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
        // Atualiza os dados do formulario.
        DaoSql ds = new DaoSql(null,'P');
        EntradaPadrao in = new EntradaPadrao();
        
        Pessoa p = new Pessoa();
        Enderecos ed = new Enderecos();
        Contato co = new Contato();

            //Atualiza dados pessoais.
            p.setNome(txtNome.getText());
            p.setAniversario(txtDtAniversario.getText());
            p.setReligiao(txtReligiao.getText());
            p.setResponsavel(txtMissionario.getText());
            p.setObservacao(txtAreaObs.getText());
            if (cboProgItem.equals("OUTROS"))
            {
               p.setPrograma(txtAreaMat.getText());
            } else {
               p.setPrograma(cboProgItem);
            }
            if (indEstudo == 'S'){
                p.setIndEstudo('S');
            } else {
                p.setIndEstudo('N');
            }
            p.setFxEtaria(cboFxEtaria.getSelectedItem().toString());
            p.setOrigem(txtOrigem.getText());
            p.setId(Integer.parseInt(txtNumMatric.getText()));

            ed.setCep(txtNumCep.getText());
            ed.setEndereco(txtEndereco.getText());
            ed.setBairro(txtBairro.getText());
            ed.setCidade(cboUf.getSelectedItem().toString());
            ed.setCod_rua(Integer.parseInt(txtCodRua.getText()));
            ed.setTxt_complamento(txtComplemento.getText());
            ed.setCodEndereco(idEndereco);

            //Insere Contatos.
            co.setNumCelular(txtNumCel.getText());
            co.setNumFixo(txtNumFixo.getText());
            co.setIndZap(indZap);
            co.setEndEmail(txtEmail.getText());
            co.setNomeOperadora(cboOperadora.getSelectedItem().toString());
            co.setIdContato(idContato);
            
            if (!ds.sqlAtualiza(p, ed, co))
            {
              in.exibeMensagem("Erro ao atualizar os dados!", "Erro de Atualização", 0);
            } else {
              in.exibeMensagem("Dados atualizados com sucesso.", "Atualização realizada", 1);
              this.atualizaDadosForm();
            }  
            
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void btnDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletaActionPerformed
        // Botão de deleçao dos registros.
        DaoSql ds = new DaoSql(null,'P');
        EntradaPadrao in = new EntradaPadrao();
        
        if (!ds.sqlDeleta(idEndereco, idContato,Integer.parseInt(txtNumMatric.getText())))
            {
              in.exibeMensagem("Erro ao deletar o registro!", "Erro de Deleção", 0);
            } else {
              in.exibeMensagem("Registro deletado com sucesso.", "Deleção de Registro", 1);
            }
        this.limpaTexto();
    }//GEN-LAST:event_btnDeletaActionPerformed

    private void txtNumCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCepKeyTyped
        // Digitos do CEP
        vQtdCaracter = vQtdCaracter + Character.toString(evt.getKeyChar());
    }//GEN-LAST:event_txtNumCepKeyTyped

    private void txtNumCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumCepFocusLost
        // Verifica CEP digitado
        EntradaPadrao ep = new EntradaPadrao();
        if (!vQtdCaracter.equals("")){
            if (vQtdCaracter.length() < 8){
                ep.exibeMensagem("O campo CEP deve ter 8 digitos. Ex: 26183-180", "Campo CEP", 2);
                txtNumCep.setText("");
            } else {
                vNumCep = txtNumCep.getText();
            }
        } else {
          vNumCep = "Sem CEP";  
        }
        vQtdCaracter = "";
    }//GEN-LAST:event_txtNumCepFocusLost

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Botão Limpar.
        DaoSql ds = new DaoSql(null,'P');

        this.limpaTexto();
        btnInsere.setEnabled(true);
        vNumMatric = "";
        txtNumMatric.setText("");
        
        vNumMatric = ds.getMatricula();
        if (!vNumMatric.equals("-1")){
            txtNumMatric.setText(vNumMatric);
        }   
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cboProgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProgItemStateChanged
        // TODO add your handling code here
       cboProgItem = ""; 
       cboProgItem = evt.getItem().toString();
       
       if (!cboProg.getSelectedItem().equals("OUTROS")){
           txtAreaMat.setEnabled(false);
           txtAreaMat.setEditable(false);
           txtAreaMat.setBackground(Color.LIGHT_GRAY);
        } else {
           txtAreaMat.setEnabled(true);
           txtAreaMat.setEditable(true);
           txtAreaMat.setBackground(Color.WHITE);
       }
       //javax.swing.JOptionPane.showMessageDialog(null, "Valor combo: " + cboProgItem);
    }//GEN-LAST:event_cboProgItemStateChanged
public void aparenciaTela(){
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnDeleta;
    private javax.swing.JButton btnInsere;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox cboFxEtaria;
    private javax.swing.JComboBox cboOperadora;
    private javax.swing.JComboBox cboProg;
    private javax.swing.JComboBox cboUf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtAreaMat;
    private javax.swing.JTextArea txtAreaObs;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCodRua;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtDtAniversario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtMissionario;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumCel;
    private javax.swing.JFormattedTextField txtNumCep;
    private javax.swing.JFormattedTextField txtNumFixo;
    private javax.swing.JTextField txtNumMatric;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtPesqId;
    private javax.swing.JTextField txtPesqNome;
    private javax.swing.JTextField txtReligiao;
    // End of variables declaration//GEN-END:variables
}
