/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.executaveis;

import com.java.classe.basica.DaoFile;
import com.java.classe.basica.DaoSql;
import com.java.classe.basica.Pessoa;
import com.java.relatorios.classes.RelatorioJasper;
import java.util.List;


/**
 *
 * @author Paulinho
 */
public class RelMembros extends javax.swing.JFrame {

    /**
     * Creates new form RelMembros
     */
    private String vIndSelecionado = ""; /*Filtros Selecionados*/
    private String vIndEstudo = ""; /*Indica a situação de estudo biblico do cadastrado (Sim ou Não).*/
    private String vIndTipoSaida = ""; /*Tipo de saide do relatorio (Arquivo ou em Tela).*/
    private String vNomBairro = "";
    private int vCodRua = 0;
    private String vNomReligiao = "";
    private String vCaminhoRel;
    private List<Pessoa> vCursorCbo = null;
    
    public RelMembros() {
        setLocationRelativeTo(null);
        this.aparenciaTela();
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panelFiltro = new javax.swing.JPanel();
        txtNomBairro = new javax.swing.JTextField();
        txtCodRua = new javax.swing.JTextField();
        cboReligiao = new javax.swing.JComboBox();
        optBairro = new javax.swing.JRadioButton();
        optReligiao = new javax.swing.JRadioButton();
        optCodRua = new javax.swing.JRadioButton();
        panelSaida = new javax.swing.JPanel();
        optTela = new javax.swing.JRadioButton();
        optArq = new javax.swing.JRadioButton();
        btnGerar = new javax.swing.JButton();
        panelSituacao = new javax.swing.JPanel();
        optSim = new javax.swing.JRadioButton();
        optNao = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCad = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuInicial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuFiltro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatorio");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Filro"));

        cboReligiao.setToolTipText("");

        buttonGroup1.add(optBairro);
        optBairro.setText("Nome do Bairro:");
        optBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBairroActionPerformed(evt);
            }
        });

        buttonGroup1.add(optReligiao);
        optReligiao.setText("Religião:");
        optReligiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optReligiaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(optCodRua);
        optCodRua.setText("Cod. Rua:");
        optCodRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCodRuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optBairro)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optCodRua)
                            .addComponent(txtCodRua, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNomBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroLayout.createSequentialGroup()
                .addComponent(optBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addComponent(optReligiao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addComponent(optCodRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panelSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Saida"));

        buttonGroup3.add(optTela);
        optTela.setSelected(true);
        optTela.setText("Visualizar em Tela");

        buttonGroup3.add(optArq);
        optArq.setText("Salvar em Arquivo");

        javax.swing.GroupLayout panelSaidaLayout = new javax.swing.GroupLayout(panelSaida);
        panelSaida.setLayout(panelSaidaLayout);
        panelSaidaLayout.setHorizontalGroup(
            panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optTela)
                    .addComponent(optArq))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSaidaLayout.setVerticalGroup(
            panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaidaLayout.createSequentialGroup()
                .addComponent(optTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(optArq))
        );

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        panelSituacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Situação"));

        buttonGroup2.add(optSim);
        optSim.setSelected(true);
        optSim.setText("Sim");

        buttonGroup2.add(optNao);
        optNao.setText("Não");

        jLabel1.setText("Em Estudo?");

        javax.swing.GroupLayout panelSituacaoLayout = new javax.swing.GroupLayout(panelSituacao);
        panelSituacao.setLayout(panelSituacaoLayout);
        panelSituacaoLayout.setHorizontalGroup(
            panelSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSituacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optNao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSituacaoLayout.setVerticalGroup(
            panelSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(optSim)
                .addComponent(optNao))
        );

        jMenu1.setText("Ir Para");

        mnuCad.setText("Tela de Cadastro");
        mnuCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCad);
        jMenu1.add(jSeparator1);

        mnuInicial.setText("Tela inicial");
        mnuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicialActionPerformed(evt);
            }
        });
        jMenu1.add(mnuInicial);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Selecionar");

        mnuFiltro.setText("Filtros do Relatorio");
        mnuFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFiltroActionPerformed(evt);
            }
        });
        jMenu2.add(mnuFiltro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void selecionaFiltro(String pTipoFiltro){
      
     if (!pTipoFiltro.equals("N")){
            optBairro.setEnabled(true);
            optReligiao.setEnabled(true);
            optCodRua.setEnabled(true);
            panelFiltro.setEnabled(true);

        if (optBairro.isSelected()){
            txtNomBairro.setEnabled(true);
            cboReligiao.setEnabled(false);
            txtCodRua.setEnabled(false);
          if (!txtNomBairro.getText().equals("")){
              vNomBairro = txtNomBairro.getText().toUpperCase();
          }  
        } else if (optReligiao.isSelected()){
            cboReligiao.setEnabled(true);
            txtNomBairro.setEnabled(false);
            txtCodRua.setEnabled(false);
            vNomReligiao = cboReligiao.getSelectedItem().toString();
            
        } else if (optCodRua.isSelected()){
            txtCodRua.setEnabled(true);
            cboReligiao.setEnabled(false);
            txtNomBairro.setEnabled(false);
          if (!txtCodRua.getText().equals("")){
              vCodRua = Integer.parseInt(txtCodRua.getText());
          }  
        }
        
      } else {
          optBairro.setEnabled(false);
          optReligiao.setEnabled(false);
          optCodRua.setEnabled(false);
          txtCodRua.setEnabled(false);
          cboReligiao.setEnabled(false);
          txtNomBairro.setEnabled(false);
          panelFiltro.setEnabled(false);
          vNomBairro = "";
          vNomReligiao = "";
          vCodRua = 0;
          vIndSelecionado = "N";
      }
        
    }
    private void selecionaFiltro2(){
        /*Retorna para o modo default de tela.*/
          /*Opções de estudo biblico Sim/Não.*/
        if (optSim.isSelected()){
            vIndEstudo = "S";
        } else if (optNao.isSelected()){
            vIndEstudo = "N";
        }
        /*Tipo de saida do relatorio.*/
        if (optTela.isSelected()){
            vIndTipoSaida = "T";
            vCaminhoRel = "";
        } else if (optArq.isSelected()){
            vIndTipoSaida = "A";
            vCaminhoRel = new DaoFile(null).salvarArquivo();
        }  
    }
    private void getCboValor(){
        int cont;
        vCursorCbo = new DaoSql(null,'P').getComboInfo();
        cboReligiao.removeAllItems();
        for(cont =0; cont < vCursorCbo.size(); cont++){
             cboReligiao.addItem(vCursorCbo.get(cont).getReligiao());
        }
    }
    private void mnuCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Inicializar componentes do formulario,
        this.selecionaFiltro("N");
        this.getCboValor();
    }//GEN-LAST:event_formWindowOpened

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // Botão de gerar o relatorio.
        RelatorioJasper rel = new RelatorioJasper(null,'P');
        
        if (vIndSelecionado.equals("S")){
           /*Verifica quais os filtros foram selecionados para eviar para o relatorio.*/
            this.selecionaFiltro("S");
        }
        /*Seleciona a saida do relatorio.*/
        this.selecionaFiltro2();
        
        /*Chama a classe de geração do relatorio.*/
        rel.gerarRelatorio( vIndSelecionado
                           ,vNomBairro
                           ,vCodRua
                           ,vNomReligiao
                           ,vIndEstudo
                           ,vIndTipoSaida
                           ,vCaminhoRel);
        
        /*Limpa os filtros apos a geração do relatorio.*/
        this.selecionaFiltro("N");
    }//GEN-LAST:event_btnGerarActionPerformed

    private void optBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBairroActionPerformed
        // TODO add your handling code here:
        this.selecionaFiltro("S");
    }//GEN-LAST:event_optBairroActionPerformed

    private void optReligiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optReligiaoActionPerformed
        // TODO add your handling code here:
        this.selecionaFiltro("S");
    }//GEN-LAST:event_optReligiaoActionPerformed

    private void optCodRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCodRuaActionPerformed
        // TODO add your handling code here:
        this.selecionaFiltro("S");
    }//GEN-LAST:event_optCodRuaActionPerformed

    private void mnuFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFiltroActionPerformed
        // Selecionar filtros.
        vIndSelecionado = "S";
        this.selecionaFiltro("S");
    }//GEN-LAST:event_mnuFiltroActionPerformed

    private void mnuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicialActionPerformed
        // Voltar para tela inicial.
        setVisible(false);
        dispose();
    }//GEN-LAST:event_mnuInicialActionPerformed
    public void aparenciaTela(){
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cboReligiao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuCad;
    private javax.swing.JMenuItem mnuFiltro;
    private javax.swing.JMenuItem mnuInicial;
    private javax.swing.JRadioButton optArq;
    private javax.swing.JRadioButton optBairro;
    private javax.swing.JRadioButton optCodRua;
    private javax.swing.JRadioButton optNao;
    private javax.swing.JRadioButton optReligiao;
    private javax.swing.JRadioButton optSim;
    private javax.swing.JRadioButton optTela;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelSaida;
    private javax.swing.JPanel panelSituacao;
    private javax.swing.JTextField txtCodRua;
    private javax.swing.JTextField txtNomBairro;
    // End of variables declaration//GEN-END:variables
}
